# Generated by Django 5.0.4 on 2024-05-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_reference_no', models.TextField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('INACTIVE', 'Inactive'), ('PAID_IN_FULL', 'Paid in full'), ('IN_COLLECTION', 'In collection')], max_length=50)),
                ('consumer_name', models.CharField(max_length=50)),
                ('consumer_address', models.TextField()),
                ('ssn', models.CharField(max_length=11)),
            ],
        ),
    ]
